### ISSUE TITLE
Templating custom/query errors

### ISSUE THREAD

**Issue by yshiro** [gbrian/grafana-simple-sql-datasource#16]
Hi, 
I´m trying to add templating with no success. 
When I try to create a custom template with an array of values, for example "madrid,barcelona,valencia" works fine, but when I write the variable $city in the metric immediately replace the $city with the value selected on the template. 
Also when I try to create a query based template, never gets data from the query. For example, when I create a query with "select city from table" where returns my cities never gets values. 

Thanks for your support. 

Regards

**Comment by gbrian** [comment]
Hi @yshiro ,
Does it helps ? https://github.com/gbrian/grafana-simple-sql-datasource/issues/9

**Comment by yshiro** [comment]
My query for templating does not contain a timetable :\
I´ve tried on Singlestat panel and table panel. The $group alias is working, but cannot save that panels with $group because is beign replaced after I click out the panel and refresh the data.

**Comment by gbrian** [comment]
@yshiro ,
I fixed about the templates being replaced. Can you check you have latest version, please?
Guess was in this change: https://github.com/gbrian/grafana-simple-sql-datasource/commit/bac005efdc7b6589eae7b71d3a146df496c0add1

**Comment by yshiro** [comment]
Hi Gustavo, 
If I create a custom template now is working. Thanks!!
But if I create a "query" template still gets no data. 

Regards.

**Comment by yshiro** [comment]
Hi @gbrian , 

I found another "bug", when i select multiple values the first value of template it is writing ok, but the seconde value ( if I selected 2 values in multiselect) is writing the variablename=value. 

For example : 

IN ( 'madrid, city=barcelona') 

Regards!

**Comment by gbrian** [comment]
Hi @yshiro , I'm back to action!
Could it be related with issue https://github.com/gbrian/grafana-simple-sql-datasource/issues/13 ?

Thanks

**Comment by gbrian** [comment]
Sorry, automatically closing old issues after several fixes. Please reopen if the problem persists.
