### ISSUE TITLE
Error creating data source

### ISSUE THREAD

**Issue by squad1534** [gbrian/grafana-simple-sql-datasource#2]
Running Debian Jessie with Grafana 4.3.2 and simple-sql-datasource 0.0.2 when trying to add datasource I receive the following error:

Error
{"data":{"code":"MODULE_NOT_FOUND"},"status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/datasources/proxy/1","data":{"type":"test","body":null,"url":null},"retry":0,"headers":{"X-Grafana-Org-Id":1,"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":"Internal Server Error"}

Appreciate any assistance or guidance,
-David

**Comment by gbrian** [comment]
Hi @squad1534 ,
Sorry for the delay, not getting this notifications :(

Please try:
Test on your browser navigating to http://myserver:port/?con=mssql://user:name@server/database you must get a {"status":"sucess"} response.

Let me know if it worked

**Comment by squad1534** [comment]
Gustavo, thanks you for your reply! Here's what I get when I enter that URL
for my server.

 

Cannot GET /

 

Appreciate your help! Look forward to your reply.



-David

 

  _____

**Comment by gbrian** [comment]
Download latest version.

**Comment by squad1534** [comment]
Downloaded and installed latest version, received this:

 

{"name":"ConnectionError","message":"Login failed for user
'grafana'.","code":"ELOGIN"}
 
 

 

 

  _____

**Comment by gbrian** [comment]
Hi @squad1534 ,

Check credentials, url should look:
`http://myserver:port/?con=mssql://user:name@server/database`

**Comment by squad1534** [comment]
Trying:

 

This example is assuming the MSSQL user account is name "grafana"

 

http://10.0.1.X:666/?con=mssql://user:grafana@10.0.2.XX/Databasename

 

http://10.0.1.X:666/?con=mssql://grafana@10.0.2.XX/Databasename

 

http://10.0.1.X:666/?con=mssql://user:grafana:mypassword@10.0.2.XX/Databasen
ame

 

http://10.0.1.X:666/?con=mssql://grafana:mypassword@10.0.2.XX/Databasename

 

which is the correct syntax? Thanks for your support!!!

 

-d-

 

 

  _____

**Comment by gbrian** [comment]
http://10.0.1.x:666/?con=mssql://grafana:mypassword@10.0.2.XX/Databasename

Where:
grafana is the user login
mypassword ...you know ;)
10.0.2.XX sql server ip
Databasename 

Last one should be working.
please be sure there's visibility between both servers.

**Comment by squad1534** [comment]
Thanks! Here's what I'm using

 

http://10.0.1.X:666/?con=mssql://grafana:mydbpassword@10.0.2.XX/MYDBNAME
<http://10.0.1.x:666/?con=mssql://grafana:mypassword@10.0.2.XX/MYDBNAME> 

 

I receive:

 

{"name":"ConnectionError","message":"Failed to connect to grafana:1433 -
getaddrinfo ENOTFOUND grafana grafana:1433","code":"ESOCKET"}

 

I know the credentials work because I can connect with HEIDISQL and other
clients OK. Any ideas?

 

Thanks,

-d-

 

 

 

  _____

**Comment by gbrian** [comment]
Really weird :(
The con value is passed directly to mssql driver https://www.npmjs.com/package/mssql 

Looks like is trying to resolve grafana as the name of the sql server. I'll check code twice. Thanks for you patience.

**Comment by squad1534** [comment]
Appreciate your help!!! Getting this to work will be a huge help for our
team.

 

  _____

**Comment by squad1534** [comment]
Gustavo,

 

And just to add, when adding the datasource within Grafana I receive this
error:

Running Debian Jessie with Grafana 4.3.2 and simple-sql-datasource 0.0.2
when trying to add datasource I receive the following error:

Error

{"data":"","status":502,"config":{"method":"POST","transformRequest":[null],
"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/dataso
urces/proxy/2","data":{"type":"test","body":null,"url":null},"retry":0,"head
ers":{"X-Grafana-Org-Id":1,"Accept":"application/json, text/plain,
*/*","Content-Type":"application/json;charset=utf-8"}},"statusText":"Bad
Gateway"}

 

Appreciate any assistance or guidance,
-DavidErro

  _____

**Comment by gbrian** [comment]
Ok, let's recap:

### Reqs:
nodejs ver `v6.9.5` or above (test with `node -v`)

### Inrastructure
Do you have 2 or 3 servers?

X.X.X.X ? : Grafana
10.0.1.XX : sqlproxyserver
10.0.2.XX : SQL Server

1. Check all servers has visibility. Ping SQL Server from the server running `sqlproxyserver`
2. Check SQL Server has port 1433 open (firewall inbound rules)
3. Check SQL credentials by login from `sqlproxyserver` server into `SQL Server` using HEIDISQL
4. Check `sqlproxyserver` using wget/curl or browser from grafana server and using url http://10.0.1.X:666/?con=mssql://grafana:mydbpassword@10.0.2.XX/MYDBNAME

Lets see which part is not working.
Regards

**Comment by squad1534** [comment]
root@metrics:~# node -v

v7.10.0

 

Grafana server is at 10.0.1.X

Sqlproxyserver is at 10.0.1.X (same machine)

 

MSSQL Server is at 10.0.2.XX

 

I can telnet to MS SQL at 10.0.2.XX from 10.0.1.X on port 1433 and I receive
a connection

I can run HeidiSQL with username grafana and login to MS SQL on 10.0.2.XX

I had a "!" at the end of password so I changed it now when I run curl I
get:

 

{"status":"sucess"}root@metrics:~#

 

And wget:

 

.parts removed.

 

Connecting to 10.0.1.5:666... connected.

HTTP request sent, awaiting response... 200 OK

Length: 19 [application/json]

 

.parts removed..

 

 

However when I try to run test from grafana data source I receive:

 

{"data":{"code":"MODULE_NOT_FOUND"},"status":500,"config":{"method":"POST","
transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"ca
llback","url":"api/datasources/proxy/2","data":{"type":"test","body":null,"u
rl":null},"retry":0,"headers":{"X-Grafana-Org-Id":1,"Accept":"application/js
on, text/plain,
*/*","Content-Type":"application/json;charset=utf-8"}},"statusText":"Interna
l Server Error"}

**Comment by gbrian** [comment]
Great, we have a {"status":"sucess"} at least this part works fine :)

If you have access to 10.0.1.XX from the machine you are `using` grafana try to set at Datasource settings `Direct`  instead proxy.

Other thing I'll check is: open chrome/firefox developers tools and check at which line this error occurs. 

Thanks

**Comment by squad1534** [comment]
Direct did the trick!!! Thanks Gustavo!

  _____

**Comment by gbrian** [comment]
Good!
BTW it should work proxied. Can i ask you for last test? Please run `npm install` over the root folder at grafana's plugin folder. Just to be sure we are no missing references.
Thanks in advance

**Comment by squad1534** [comment]
root@metrics:/var/lib/grafana/plugins/grafana-simple-sql-datasource-master#
npm install

npm WARN The package q is included as both a dev and production dependency.

 

up to date in 15.832s

 

 

   q───────────────────────────────────
──r

   │                                     │

   │   Update available 5.0.2 → 5.0.3    │

   │     Run npm i -g npm to update      │

   │                                     │

   t───────────────────────────────────
──s

 

  _____

**Comment by gbrian** [comment]
+1 ...and did it work proxied after? Thanks

**Comment by squad1534** [comment]
No 

 

{"data":{"code":"MODULE_NOT_FOUND"},"status":500,"config":{"method":"POST","
transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"ca
llback","url":"api/datasources/proxy/2","data":{"type":"test","body":null,"u
rl":null},"retry":0,"headers":{"X-Grafana-Org-Id":1,"Accept":"application/js
on, text/plain,
*/*","Content-Type":"application/json;charset=utf-8"}},"statusText":"Interna
l Server Error"}

  _____

**Comment by squad1534** [comment]
Happy to help you test if you need.

 

  _____

**Comment by Bazzel001** [comment]
Hello,

I have gone though the setup and fixed a couple of issues but when adding a new datasource i am getting "HTTP Error
Internal Server Error" 

This is with access set to direct, if its set as Proxy then i get the following:
ReferenceError: res is not defined
    at err (C:\grafsql\dist\serverside\sqlproxyserver.js:54:28)
    at C:\grafsql\dist\serverside\sqlproxyserver.js:57:16
    at Layer.handle [as handle_request] (C:\grafsql\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\grafsql\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\grafsql\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\grafsql\node_modules\express\lib\router\layer.js:95:5)
    at C:\grafsql\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\grafsql\node_modules\express\lib\router\index.js:335:12)
    at next (C:\grafsql\node_modules\express\lib\router\index.js:275:10)
    at jsonParser (C:\grafsql\node_modules\body-parser\lib\types\json.js:103:7)

I had to run the NPM install in 2 locations to get the URL to confirm success but this datasource will not add.

Hopefully this is the right place/related.

Thanks

**Comment by gbrian** [comment]
@Bazzel001 ,

Good catch there's a big error there :( I'll fix asap:

    var err = (message) => res.status(500).send(message);
    app.get("/", function(req, res){
      if(!req.query.con){
        return err("Missing parameter `con` with connection details. "
        + "Example: con=mssql://username:password@server/database");
      }

Seems to be failing because missing the `con` parameter.
Please follow this steps:
 * Download latest version and test serverside by navigating to this url:   http://server:port (or 666)/?con=mssql://dbuser:dbpwd@SQL_SERVER/DATABASENAME

You must get a `success` message.

Keep me posted :)

**Comment by Bazzel001** [comment]
@gbrian 

I have downloaded and tested this morning.

I am still able to get a success message using the URL in a browser however the issue persists trying to add the datasource. The reference error is the same as it was previously when trying to use the proxy setup.

Direct will not connect.

EDIT: I have noticed that the revisions listed in the latest commit did not update. i have changed these manually and i do not get the Reference error showing in the proxy log now however i still cannot add the datasource with direct or proxy

Thanks

**Comment by gbrian** [comment]
Hi @Bazzel001,

I build this up from https://github.com/grafana/simple-json-datasource and it works fine with proxy .... I compared many parts but found nothing.
Still working on it, sadly with not too much time :( !

**Comment by robisonaz** [comment]
@Bazzel001 and @gbrian

Good night, I have the same problem. Accessing with browser appears the message status "success". But with Grafana using datasource SIMPLEJSON does not work. Here is an error "HTTP Error Internal Server Error"
 node -v v6.11.2

node grafana-simple-sql-datasource/dist/serverside/sqlproxyserver.js
Server is listening to port 666
ReferenceError: res is not defined
    at err (/root/grafana-simple-sql-datasource/dist/serverside/sqlproxyserver.js:54:28)
    at /root/grafana-simple-sql-datasource/dist/serverside/sqlproxyserver.js:57:16
    at Layer.handle [as handle_request] (/root/grafana-simple-sql-datasource/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/grafana-simple-sql-datasource/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/grafana-simple-sql-datasource/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/grafana-simple-sql-datasource/node_modules/express/lib/router/layer.js:95:5)
    at /root/grafana-simple-sql-datasource/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/root/grafana-simple-sql-datasource/node_modules/express/lib/router/index.js:335:12)
    at next (/root/grafana-simple-sql-datasource/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/root/grafana-simple-sql-datasource/node_modules/body-parser/lib/types/json.js:103:7)

**Comment by gbrian** [comment]
@robisonaz 
I fixed that, please download the latest version.
After you'll see the error.

**Comment by robisonaz** [comment]
Good night, I downloaded the version that is in that site. Even so, the error persists.
https://github.com/gbrian/grafana-simple-sql-datasource

URL to SIMPLEJSON -> http://192.168.56.30:666/?con=mssql://grafana:PASSWD@192.168.56.10/DATABASE

![image](https://user-images.githubusercontent.com/26012053/29798353-ef8e53cc-8c32-11e7-8d62-bfa81b02a50b.png)

**Comment by gbrian** [comment]
@robisonaz , 
Sadly "proxy" version is not working, trying to find teh time to fix :( Check here: #https://github.com/gbrian/grafana-simple-sql-datasource/issues/1
Use "Direct" when possible

**Comment by robisonaz** [comment]
@gbrian , i tried with direct and it did not work, same error. Console error does not occur using direct.

![image](https://user-images.githubusercontent.com/26012053/29823122-15be1a84-8ca4-11e7-8be7-d0382a6f6ca3.png)

![image](https://user-images.githubusercontent.com/26012053/29823127-1bcb255c-8ca4-11e7-8930-32938cb695aa.png)

**Comment by gbrian** [comment]
@robisonaz ,
I apology for the time this is taken as should be quite basic :(
Just tested and worked with "direct". Please run the Url directly on the browser you must see a "success" message. Don't worry about setting up grafana until not having this step working.

![image](https://user-images.githubusercontent.com/767180/29827137-69d3afbe-8cd9-11e7-997f-3e4890dc9184.png)

**Comment by robisonaz** [comment]
Hi, after placing the port of MSSQL according to URL http://192.168.56.30:666/?con=mssql?grafica:xxxx@192.168.56.10:1433/Protheus12 working. Try to run select occurred following error.

![image](https://user-images.githubusercontent.com/26012053/29840476-8da2926c-8cd8-11e7-9855-3d6b3f62da3e.png)

![image](https://user-images.githubusercontent.com/26012053/29840477-915e5d5a-8cd8-11e7-9c40-61720bdb6ef6.png)

![image](https://user-images.githubusercontent.com/26012053/29840485-96282d3e-8cd8-11e7-89dc-591b21f3bab2.png)

![image](https://user-images.githubusercontent.com/26012053/29840494-9a89c464-8cd8-11e7-99ea-366899c952ba.png)

**Comment by gbrian** [comment]
@robisonaz ,
Just updated the project this morning after fixing some weird behaviors.
Can you please download and restart server/grafana?
If error persists can you post:
 * url
 * body json (raw view)
(remeber to remove sensitive data)
Thanks

**Comment by robisonaz** [comment]
@gbrian 
I only updated src /serverside /sqlproxyserver.js
Error has changed, prints and information follows:
URL: http://192.168.56.30:666/?con=mssql://grafana:password@192.168.56.10:1433/database

![image](https://user-images.githubusercontent.com/26012053/29873870-49f71914-8d6b-11e7-88ef-9a08b93a748c.png)

![image](https://user-images.githubusercontent.com/26012053/29873879-4e5618de-8d6b-11e7-95bf-76434d90d34c.png)

What do you need?
Need to install grafana-simple-sql-datasource as a grafana plugin?

**Comment by gbrian** [comment]
@robisonaz 
First with the new version you need to change URL (remove the '?' ) like this: **http://192.168.56.30:666/con=mssql://grafana:password@192.168.56.10:1433/database**

Apart from that, I'll suggest using PostMan to test same requests send by grafana.

**Comment by robisonaz** [comment]
@gbrian 
I tried but failed.

Postman, I will install.

![image](https://user-images.githubusercontent.com/26012053/29877715-c56605a0-8d76-11e7-84f2-1e8450747665.png)

![image](https://user-images.githubusercontent.com/26012053/29877046-d5a3ce2c-8d74-11e7-9b21-14628c4faa37.png)

**Comment by gbrian** [comment]
@robisonaz  and everybody in this post,
I apology I was missing a commit (OMG! SO SORRY!!)
Just updated the repository I encourage you to download again.
Again, sorry for the inconvenieces.

**Comment by zmarty** [comment]
Sadly this still does not work for me. And the URL does need a question mark in the version I downloaded right now.

If I download this locally using wget I get the success JSON.
http://localhost:666/?con=mssql://user:pass@serverhost:1433/dbname?encrypt=true

But when I try to add the data source with Access = proxy, it does not work:

`
{"data":{"error":"Internal Server Error","response":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>TypeError: Cannot read property &#39;1&#39; of null<br> &nbsp; &nbsp;at SQLProxyServer.loadProvider.SQLProxyServer.loadAPI.SQLProxyServer.execCommand.SQLProxyServer.getConnection.req [as getConnection] (/var/lib/grafana/plugins/grafana-simple-sql-datasource-master/dist/serverside/sqlproxyserver.js:37:44)<br> &nbsp; &nbsp;at /var/lib/grafana/plugins/grafana-simple-sql-datasource-master/dist/serverside/sqlproxyserver.js:71:13<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/var/lib/grafana/plugins/grafana-simple-sql-datasource-master/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/var/lib/grafana/plugins/grafana-simple-sql-datasource-master/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/var/lib/grafana/plugins/grafana-simple-sql-datasource-master/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/var/lib/grafana/plugins/grafana-simple-sql-datasource-master/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /var/lib/grafana/plugins/grafana-simple-sql-datasource-master/node_modules/express/lib/router/index.js:281:22<br> &nbsp; &nbsp;at param (/var/lib/grafana/plugins/grafana-simple-sql-datasource-master/node_modules/express/lib/router/index.js:354:14)<br> &nbsp; &nbsp;at param (/var/lib/grafana/plugins/grafana-simple-sql-datasource-master/node_modules/express/lib/router/index.js:365:14)<br> &nbsp; &nbsp;at Function.process_params (/var/lib/grafana/plugins/grafana-simple-sql-datasource-master/node_modules/express/lib/router/index.js:410:3)</pre>\n</body>\n</html>\n","message":"Internal Server Error"},"status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/datasources/proxy/2","data":{"type":"test","body":null,"url":null},"retry":0,"headers":{"X-Grafana-Org-Id":1,"X-Grafana-NoCache":"true","Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":"Internal Server Error"}`

**Comment by gbrian** [comment]
Hi @zmarty ,

Just realized a `typo` in your url: 
`http://localhost:666/?con=mssql://user:pass@serverhost:1433/dbname?encrypt=true`
Should be
`http://localhost:666/con=mssql://user:pass@serverhost:1433/dbname?encrypt=true`

Can you try again please without this `?` before `con=`?
